DROP TABLE TAKEN;
DROP TABLE REQUIRED;

create table TAKEN(
    STUDENT VARCHAR2(30) NOT NULL,
    COURSE VARCHAR2(30) NOT NULL
);

create table REQUIRED(
    COURSE VARCHAR2(30) NOT NULL
);

INSERT INTO TAKEN(STUDENT, COURSE) VALUES ('Robert','Databases');
INSERT INTO TAKEN(STUDENT, COURSE) VALUES ('Robert','Programming Languages');
INSERT INTO TAKEN(STUDENT, COURSE) VALUES ('Susie','Databases');
INSERT INTO TAKEN(STUDENT, COURSE) VALUES ('Susie','Operating Systems');
INSERT INTO TAKEN(STUDENT, COURSE) VALUES ('Julie','Programming Languages');
INSERT INTO TAKEN(STUDENT, COURSE) VALUES ('Julie','Machine Learning');
INSERT INTO TAKEN(STUDENT, COURSE) VALUES ('Emilie','Operating Systems');


INSERT INTO REQUIRED(COURSE) VALUES ('Databases');
INSERT INTO REQUIRED(COURSE) VALUES ('Programming Languages');

COMMIT;